# Generated by Django 4.2.1 on 2023-06-03 13:08

from django.db import migrations


def populate_db(apps, schema_editor):
    Teacher = apps.get_model("schoolapp", "Teacher")
    Student = apps.get_model("schoolapp", "Student")
    Homework = apps.get_model("schoolapp", "Homework")
    CompletedHomework = apps.get_model("schoolapp", "CompletedHomework")
    db_alias = schema_editor.connection.alias

    Teacher_instance = Teacher(name="Teacher Teacherov")
    Teacher.objects.using(db_alias).bulk_create([Teacher_instance])

    Student_instance = Student(name="Test Testov")
    Student.objects.using(db_alias).bulk_create([Student_instance])

    Homework_instance = Homework(teacher=Teacher_instance)
    Homework.objects.using(db_alias).bulk_create([Homework_instance])

    CompletedHomework.objects.using(db_alias).bulk_create(
        [
            CompletedHomework(
                homework=Homework_instance,
                student=Student_instance,
            )
        ]
    )


class Migration(migrations.Migration):
    dependencies = [
        ("schoolapp", "0001_initial"),
    ]

    operations = [migrations.RunPython(populate_db)]
